import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SVGs from "./components/SVGs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CastMate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' />
        <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' />
      </head>
      <body className="content-container">
        <SVGs />
        {children}
      </body>
    </html>
  );
}
